# Generated by Django 5.2 on 2025-05-11 15:26

import django.db.models.deletion
import iservice.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50, verbose_name='location_name')),
                ('location_description', models.TextField(blank=True, null=True, verbose_name='location_description')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name="o'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': 'Joylashuv',
                'verbose_name_plural': 'Joylashuvlar',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Iltimos mijozning to'liq ismini kiriting.", max_length=50, validators=[iservice.validators.validate_f_name], verbose_name='toliq_ism')),
                ('p_number', models.CharField(error_messages={'invalid': 'Iltimos, to‘g‘ri telefon raqamini kiriting!'}, help_text="Iltimos, telefon raqamni to'ri kiriting. Masalan: +998123456789", max_length=13, validators=[iservice.validators.PhoneValidator()], verbose_name='telefon_raqam')),
                ('email', models.EmailField(blank=True, help_text='Iltimos, Email manzilingizni kiriting.', max_length=254, null=True, verbose_name='pochta')),
                ('description', models.TextField(blank=True, null=True, verbose_name='tavsifi')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateField(auto_now=True, verbose_name="o'zgartirilgan vaqti")),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iservice.location', verbose_name='joylashuv')),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200, verbose_name='task title')),
                ('role', models.CharField(choices=[('To Do', 'todo'), ('In Progress', 'progress'), ('In Review', 'review'), ('Done', 'done')], default='To Do', max_length=20)),
                ('deadline', models.DateField(verbose_name='deadline')),
                ('price', models.DecimalField(decimal_places=1, max_digits=12, verbose_name='price')),
                ('payment_t', models.CharField(choices=[('Cash', 'cash'), ('Card', 'card'), ('Process', 'process')], default='Process', max_length=20)),
                ('cost', models.DecimalField(decimal_places=1, default=0, max_digits=12, verbose_name='cost')),
                ('program', models.CharField(default='.', max_length=200, verbose_name='program')),
                ('program_sum', models.DecimalField(decimal_places=1, default=0, max_digits=12, verbose_name='program_summ')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateField(auto_now=True, verbose_name="o'zgartirilgan vaqti")),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iservice.customer', verbose_name='customer')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iservice.location', verbose_name='joylashuv')),
            ],
            options={
                'verbose_name': 'Vazifa',
                'verbose_name_plural': 'Vazifalar',
            },
        ),
    ]
