# Generated by Django 5.2 on 2025-05-12 23:00

import iservice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iservice', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='cost',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=12, validators=[iservice.models.validate_cost], verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='task',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=12, validators=[iservice.models.validate_cost], verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='task',
            name='program',
            field=models.CharField(blank=True, default='.', max_length=200, null=True, verbose_name='program'),
        ),
        migrations.AlterField(
            model_name='task',
            name='program_sum',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=12, null=True, validators=[iservice.models.validate_cost], verbose_name='program_summ'),
        ),
    ]
