# Generated by Django 5.2 on 2025-05-12 23:02

import iservice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iservice', '0003_alter_task_cost_alter_task_price_alter_task_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=12, null=True, validators=[iservice.models.validate_cost], verbose_name='cost'),
        ),
    ]
